### ISSUE TITLE
Alternative command for `--enable_burn_mode`

### ISSUE THREAD

**Issue by lmore377** [bishopdynamics/superbird-tool#3]
If you replace line 129 in superbird_tool.py with this:

`dev.bulkcmd(r'setenv storeargs "${storeargs} if gpio input GPIOA_3; then run update; fi;"')`

It'll make it to where the car thing only goes into burn mode when preset 4 is held down while booting. You could also make it to where the user can choose which button should be held down by changing GPIOA_3 to one of the following:
Preset 1: GPIOA_0
Preset 2: GPIOA_1
Preset 3: GPIOA_2
Preset 4: GPIOA_3
Back: GPIOA_5
Select: GPIOZ_7
Power/Menu: GPIOAO_3

**Comment by bishopdynamics** [comment]
Nice! I went ahead and added `--enable_burn_mode_button` option. Thanks!
