### ISSUE TITLE
Fails while flashing boot_adb_kernel

### ISSUE THREAD

**Issue by 0oERASERo0** [bishopdynamics/superbird-tool#6]
Hi, I used the "--boot_adb_kernel" option and it fails. 
And I couldn't get the Logo stuck to let me flash the kernel
Does using wsl with usbipd matters?
![superbird](https://user-images.githubusercontent.com/116210896/199648349-8fbe3bb6-7f66-47b4-ad74-ec87e81e89e8.PNG)

**Comment by bishopdynamics** [comment]
Give it a `git pull` to grab the latest version.
It looks like you're using `0.0.3`, but I *think* i fixed the issue you're seeing with `0.0.4`

**Comment by 0oERASERo0** [comment]
I git pulled, restored the stock env and follow the steps again.
However, it didn't work. I think the problem is that `--enable_burn_mode` didn't work for me.
Because it didn't enable USB Burn Mode at every boot.
When I plug it in, the Car thing show the logo for a sec and GX-Chip appeared.
After a few sec, it reboots itself and boot normally instead of stuck at the booting logo. 
![image](https://user-images.githubusercontent.com/116210896/199652304-a4f8271c-095b-438a-a67c-ec36aebb5592.png)

**Comment by 0oERASERo0** [comment]
*Failure to gain ADB access on normal boot*
`https://github.com/frederic/superbird-bulkcmd/issues/14`

Maybe it's due to an update changing some memory addresses?

**Comment by bishopdynamics** [comment]
Hmm, I haven't personally tried it with WSL + usbipd yet, maybe there's something odd I need to account for WRT USB device population. Let me set this up tomorrow and I'll see what's going on

**Comment by 0oERASERo0** [comment]
Ok thanks!

Here's are the resources in case you need it. 

*WSL & usbipd*
`https://learn.microsoft.com/en-us/windows/wsl/connect-usb`

**Comment by bishopdynamics** [comment]
It would be valuable to see if you get the same result if you do it natively from windows, instead of using WSL. You will need to install python of course, and the needed package from pip.

**Comment by 0oERASERo0** [comment]
Well, I used a ubuntu live USB and do the work on it.
And, it works perfectly now! I think is the usbipd is the problem, because it has to reconnect the devices every time if the carthing reboots. 
Thanks for the scripts!

**Comment by bishopdynamics** [comment]
Happy to help!
